version: "3.9"

services:
  # ------------------------------------------
  # 1. BAZA PODATKOV
  baza-mongo: 
    image: mongo:latest
    container_name: paketnik_baza
    ports: 
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  # ---------------------------------------------
  # 2. GLAVNI PROJEKT (RAI)
  backend: 
    build: 
      context: ./RAI/backend
    container_name: paketnik_api
    ports: 
      - "3000:3000"
    depends_on:
      - baza-mongo
    restart: unless-stopped

  glavna-spletna-stran: 
    build: 
      context: ./RAI/frontend
    container_name: paketnik_frontend
    ports: 
      - "3001:3001"
    environment:          
      - HOST=0.0.0.0
    stdin_open: true
    tty: true 
    depends_on:
      - backend
    restart: unless-stopped

  #-------------------------------------------------
  # 3. ORV - Prepoznava obrazov
  model-api-obraz:
    build:
      context: ./ORV/api
    container_name: face2fa-api
    ports:
      - "8000:8000"
    volumes:
      - ./ORV/api/model:/app/model:ro
    environment:
      - MODEL_PATH=model/resnet18_prepoznava_obrazov.pth
      - AUTH_THRESHOLD=0.80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  predobdelava:
    build:
      context: ./ORV
      dockerfile: Dockerfile.predobdelava
    container_name: face2fa-predobdelava
    volumes:
      - ./ORV:/app
    command: ["python", "predobdelava.py"]
    profiles: ["tools"]
    restart: "no"

  # ------------------------------------------------------
  # 4. ANDROID APP ( za generiranje APK-ja)
  # Ne zaganja avtomatsko. Za zagnat APK, vpišeš:
  # docker compose --profile build up android-build
  android-build:
    build:
      context: ./PJ
    container_name: android_apk_builder
    profiles: ["build"]
    restart: "no"

volumes:
  mongo_data: